/*
add bag of holding
*/


OUTER_SPRINT bagres  ~d2#wbag~

ACTION_IF !(FILE_EXISTS ~override/%bagres%.ITM~) BEGIN

OUTER_SPRINT descimage  ~d2dbag~
COPY ~%wbag%/eebagdesc.bam~  ~override/%descimage%.bam~

ACTION_IF (GAME_IS ~bgee bg2ee eet~) BEGIN
  COPY ~%wbag%/d2hbee1.ITM~  ~override/%bagres%.ITM~
    SAY NAME1 ~%weaponsack_name%~ SAY UNIDENTIFIED_DESC ~%weaponsack_desc%~
    SAY NAME2 ~%weaponsack_name%~
    WRITE_ASCII 0x3a ~%bagres%~ #8
    WRITE_ASCII 0x58 ~%descimage%~ #8

  COPY ~%wbag%/d2hbee1.STO~  ~override/%bagres%.STO~
    SAY 0xc ~%weaponsack_name%~
    LPF cannot_add_items END
END

ACTION_IF (GAME_IS ~iwdee~) BEGIN
  COPY ~%wbag%/d2hbee0.ITM~  ~override/%bagres%.ITM~
    SAY NAME1 ~%weaponsack_name%~
    SAY NAME2 ~%weaponsack_name%~ SAY DESC ~%weaponsack_desc%~
    WRITE_ASCII 0x3a ~%bagres%~ #8
    WRITE_ASCII 0x58 ~%descimage%~ #8

  COPY ~%wbag%/d2hbee0.STO~  ~override/%bagres%.STO~
    SAY 0xc ~%weaponsack_name%~
    LPF cannot_add_items END
END

ACTION_IF (GAME_IS ~pstee~) BEGIN
  COPY ~%wbag%/pstbag.ITM~  ~override/%bagres%.ITM~
    SAY NAME1 ~%weaponsack_name%~
    SAY NAME2 ~%weaponsack_name%~ SAY DESC ~%weaponsack_desc%~
    WRITE_ASCII 0x3a ~%bagres%~ #8
    WRITE_ASCII 0x44 WMTPOT #8       // ground bottle icon (match Argent77's bag mod)
    WRITE_ASCII 0x10 INT_12O1 #8     // drop sound
    WRITE_ASCII 0x58 INT_12O #8      // pick up sound

  COPY ~%wbag%/pstbag.STO~  ~override/%bagres%.STO~
    SAY 0xc ~%weaponsack_name%~
    LPF cannot_add_items END
END

COPY ~%wbag%/%bagres%.BAM~  ~override~

END

INCLUDE ~%MOD_FOLDER%/install/wbagfill.tph~



//
//Add scripts for Dev mode option

ACTION_IF ((IS_AN_INT devmode) AND (devmode = 8)) BEGIN
ACTION_IF !(RESOURCE_CONTAINS ~baldur.bcs~  ~%bagres%~) BEGIN

  ACTION_IF (GAME_INCLUDES ~bg2~) BEGIN
    EXTEND_BOTTOM ~AR0602.BCS~  ~%wbag%/wbag-imoen.BAF~
  END 
  
  ACTION_IF (GAME_INCLUDES ~sod~) BEGIN
    EXTEND_BOTTOM ~bd0120.BCS~  ~%wbag%/wbag-sodscript.BAF~
  END

  ACTION_FOR_EACH script IN ~BPHUB~  ~ohbhub~ BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~%script%.BCS~) BEGIN
      EXTEND_BOTTOM ~%script%.BCS~  ~%wbag%/wbag-bpscript.BAF~
    END
  END

  ACTION_FOR_EACH script IN ~BALDUR~  ~BALDUR25~  ~bdbaldur~ BEGIN
    ACTION_IF (FILE_EXISTS_IN_GAME ~%script%.BCS~) BEGIN
      EXTEND_TOP ~%script%.BCS~  ~%wbag%/wbag-script.BAF~
    END
  END

END
END


/*
*/